### ISSUE TITLE
Update to Cake.AzureDevOps 0.4.2

### ISSUE THREAD

**Issue by christianbumann** [cake-contrib/Cake.Issues.PullRequests.AzureDevOps#155]
The version of `Cake.AzureDevOps` should be updated.
At this time creating new `AzureDevOpsPullRequestSettings` will fail running on `Azure Pipelines` because of the issue ` Failed to read the SYSTEM_PULLREQUEST_PULLREQUESTID environment variable`. 
The [Cake.AzureDevOps 0.4.2 release](https://github.com/cake-contrib/Cake.AzureDevOps/releases) bring some fixes.

**Comment by pascalberger** [comment]
The above error only occurs when not running a pull request triggered build. Up until now the calling script needs to make sure the propery alias / settings are passed. With Cake.AzureDevOps 0.4.2 this has beend improved, but it is not something which should be dictated by this addin but by the consuming build script. Cake by default doesn't load dependencies on addins. While theres a `loaddependencies=true` pre-processor directive to enforce this, it will require the consumer to use a specific syntax in his script to make the addin work. In which case I prefer to give the consumer full control over which version of dependency is running.

So this addin requires Cake.AzureDevOps 0.4.x, and it is up to the build script to decide which version of Cake.AzureDevOps it should use. Therefore it is OK to build this addin against Cake.AzureDevOps 0.4.0, since there are no breaking changes in the API.
